### ISSUE TITLE
KeyError: 'DISPLAY' in stop

### ISSUE THREAD

**Issue by ryancc9** [cgoldberg/xvfbwrapper#27]
Hi,  
Thanks for the awesome wrapper!
I'm getting the below error running dryscrape with xvfbwrapper.  
Ubuntu 16.04.2 LTS (Ubuntu Mate)
Python 2.7.12
xvfbwrapper-0.2.9

Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/xvfbwrapper.py", line 84, in stop
    del os.environ['DISPLAY']
  File "/usr/lib/python2.7/os.py", line 498, in __delitem__
    del self.data[key]
KeyError: 'DISPLAY'

I'm not sure this is the best solution, but I was able to fix this by adding "if 'DISPLAY' in os.environ:" to check that 'DISPLAY' actually exists.
```
            if self.orig_display is None:
                if 'DISPLAY' in os.environ:
                   del os.environ['DISPLAY']

```

**Comment by gariel** [comment]
I have the same problem, to temporary fix I added the `DISPLAY` key on `os.environ` dict before start:

```python
    def start(self):
        # fixing an exception raised in xvfb
        os.environ['DISPLAY'] = ':0'

        self._xvfb.start()
```

Python 3.7.3
xvfbwrapper-0.2.9

**Comment by cgoldberg** [comment]
This should be fixed with #42 and #54
