### ISSUE TITLE
Failure when DISPLAY is empty

### ISSUE THREAD

**Issue by vog** [cgoldberg/xvfbwrapper#39]
This is possibly related to #27.

If DISPLAY is an empty string (rather than being unset), `xvfbwrapper` fails with the following exception:

```python
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/lib/python3/dist-packages/xvfbwrapper.py", line 50, in __init__
    self.orig_display = os.environ['DISPLAY'].split(':')[1]
IndexError: list index out of range
```

**Comment by ags-dy** [comment]
I am also affected by this bug

**Comment by cgoldberg** [comment]
Good catch... I will fix this. 

Sorry for the very late reply!

**Comment by cgoldberg** [comment]
This should be fixed with #42 and #54
